# Fast DIBEM potencial — RBF × compression comparison
# for paper: Fast_DIBEM_potencial - h2
#
# Compares DIBEM mass operator assembly/solve quality:
#   RBF:     PHS1, PHS2, PHS3, FundamentalRBF (u* with zero-row-sum F diag)
#   method:  dense, hmatrix, h2, fmm
#
# Metric on Helmholtz correlato helm1d (κ=2): interior relative L2 error
# and wall times for H/G, M (DIBEM), and solve.
#
# Run:
#   julia --project=. scripts/fast_dibem_potencial_rbf_compare.jl
#
# ENV:
#   DIBEM_NDIVS=6,10,14,20
#   DIBEM_TIPO=1
#   DIBEM_FR=2.0
#   DIBEM_OUT=<paper-dir or plots/>
#   DIBEM_QUICK=1   # single ndiv smoke
#   DIBEM_METHODS=dense,hmatrix,fmm
using DrWatson
@quickactivate :BEM
using LinearAlgebra
using Printf
using Dates

include(datadir("Laplace", "Laplace_dad.jl"))
include(datadir("Laplace", "potencial_problems.jl"))
include(datadir("Laplace", "wave_propagation.jl"))
include(datadir("Laplace", "helmholtz_problems.jl"))

const PAPER = raw"C:\Users\lucas.s.campos\OneDrive\artigos\escritos\2025\Fast_DIBEM_potencial - h2"
const OUTDIR = get(ENV, "DIBEM_OUT", isdir(PAPER) ? PAPER : projectdir("plots"))
const TIPO   = parse(Int, get(ENV, "DIBEM_TIPO", "1"))
const FR     = parse(Float64, get(ENV, "DIBEM_FR", "2.0"))
const NPG    = parse(Int, get(ENV, "DIBEM_NPG", "12"))
const QUICK  = parse(Bool, get(ENV, "DIBEM_QUICK", "0"))
const ATOL   = parse(Float64, get(ENV, "DIBEM_ATOL", "1e-5"))

_parse_ints(s) = parse.(Int, split(s, ','; keepempty=false))
const NDIVS = QUICK ? [6] : _parse_ints(get(ENV, "DIBEM_NDIVS", "6,10,14,20"))

const METHODS = Symbol.(split(
    get(ENV, "DIBEM_METHODS", "dense,hmatrix,fmm"), ','; keepempty=false))
const RBF_NAMES = (:PHS1, :PHS2, :PHS3, :FS)

function make_rbf(name::Symbol, dad)
    if name === :PHS1
        return PHS1(0)
    elseif name === :PHS2
        return PHS2(0)
    elseif name === :PHS3
        return PHS3(0)
    elseif name === :FS
        return fundamental_rbf(dad; poly_deg=-1)
    else
        error("unknown rbf $name")
    end
end

function _rel(a, b)
    nb = norm(b)
    return nb > 0 ? norm(a .- b) / nb : Inf
end

function run_one(; ndiv, method::Symbol, rbf_name::Symbol, κ=FR, tipo=TIPO, npg=NPG)
    msh = helm1d_mesh(; ndiv=ndiv, nome="dibem_$(rbf_name)_$(method)_$ndiv")
    dad = format2d(msh, Laplace(1.0); tipo=tipo, pontointerno=false)
    n_side = max(3, ndiv)
    set_internal_grid!(dad; nx=n_side, ny=n_side, x=(0.0, 1.0), y=(0.0, 1.0), pad=1e-3)
    ana = ana_helm1d(κ)
    attach_analytical!(dad, ana)

    rbf = make_rbf(rbf_name, dad)

    t_HG = @elapsed H_G_full_direct(dad; npg=npg)
    t_M = @elapsed begin
        if method === :dense
            DIBEM(dad; method=:dense, rbf=rbf)
        else
            DIBEM(dad; method=method, rbf=rbf, atol=ATOL, rtol=ATOL, nmax=24)
        end
    end

    t_sol = @elapsed solve(dad; blocks=true, M=dad.M, κ2=κ^2)

    n, nt = dad.n, dad.nt
    Ti = @view dad.T[n+1:nt]
    Tana_i = [float(ana.u(p)) for p in dad.internalNodes]
    err_i = _rel(Ti, Tana_i)
    Tb = @view dad.T[1:n]
    Tana_b = [float(ana.u(p)) for p in dad.Nodes]
    err_b = _rel(Tb, Tana_b)

    # F zero-row property (dense path only)
    f_rowsum = NaN
    if has_cache(dad, :dibem_F)
        F = dad.dibem_F
        f_rowsum = maximum(abs, F * ones(size(F, 1)))
    end

    return (;
        rbf=String(rbf_name), method=String(method), ndiv, tipo,
        n=dad.n, ni=dad.ni, nt=dad.nt, κ,
        t_HG, t_M, t_sol, t_total=t_HG + t_M + t_sol,
        err_i, err_b, f_rowsum,
    )
end

const HEADER = ("rbf", "method", "ndiv", "n", "ni", "nt",
                "t_HG", "t_M", "t_sol", "t_total", "err_i", "err_b", "F_rowsum_max")

function write_tsv(path, rows)
    mkpath(dirname(path))
    open(path, "w") do io
        println(io, join(HEADER, '\t'))
        for r in rows
            @printf(io,
                "%s\t%s\t%d\t%d\t%d\t%d\t%.6e\t%.6e\t%.6e\t%.6e\t%.6e\t%.6e\t%.6e\n",
                r.rbf, r.method, r.ndiv, r.n, r.ni, r.nt,
                r.t_HG, r.t_M, r.t_sol, r.t_total, r.err_i, r.err_b,
                isnan(r.f_rowsum) ? NaN : r.f_rowsum)
        end
    end
    return path
end

function write_latex_table(path, rows; ndiv_pick=nothing)
    # pick finest ndiv present
    nd = something(ndiv_pick, maximum(r.ndiv for r in rows))
    sub = filter(r -> r.ndiv == nd, rows)
    isempty(sub) && return nothing
    open(path, "w") do io
        println(io, "% auto-generated by fast_dibem_potencial_rbf_compare.jl  ndiv=$nd")
        println(io, "\\begin{table}[H]")
        println(io, "\\centering")
        println(io, "\\caption{DIBEM mass operator: RBF basis vs compression (helm1d, \$\\kappa=$(FR)\$, \$D\\equiv n_{\\mathrm{div}}=$nd\$). Relative interior error \$e_i\$ and DIBEM assembly time.}")
        println(io, "\\label{tab:dibem_rbf_compress}")
        println(io, "\\begin{tabular}{llrrrr}")
        println(io, "\\hline")
        println(io, "RBF & method & \$n_b\$ & \$n_i\$ & \$e_i\$ & \$t_M\$ [s] \\\\")
        println(io, "\\hline")
        for r in sort(sub; by=r -> (r.rbf, r.method))
            @printf(io, "%s & %s & %d & %d & %.2e & %.3f \\\\\n",
                r.rbf, r.method, r.n, r.ni, r.err_i, r.t_M)
        end
        println(io, "\\hline")
        println(io, "\\end{tabular}")
        println(io, "\\end{table}")
    end
    return path
end

function print_table(rows)
    println("-"^100)
    @printf("%-6s %-8s %4s %5s %5s %10s %10s %10s\n",
        "rbf", "method", "ndiv", "n", "ni", "err_i", "t_M", "t_tot")
    for r in rows
        @printf("%-6s %-8s %4d %5d %5d %10.2e %10.3f %10.3f\n",
            r.rbf, r.method, r.ndiv, r.n, r.ni, r.err_i, r.t_M, r.t_total)
    end
    println("="^100)
end

function main()
    println("="^100)
    println(" Fast DIBEM potencial — RBF × compression")
    println(" κ=$FR  ndivs=$NDIVS  methods=$METHODS  rbfs=$RBF_NAMES")
    println(" out=$OUTDIR")
    println("="^100)

    rows = NamedTuple[]
    for ndiv in NDIVS, rbf_name in RBF_NAMES, method in METHODS
        tag = "ndiv=$ndiv rbf=$rbf_name method=$method"
        print("▸ $tag … "); flush(stdout)
        try
            r = run_one(; ndiv=ndiv, method=method, rbf_name=rbf_name)
            push!(rows, r)
            @printf("err_i=%.2e  t_M=%.2fs  t_tot=%.2fs  Frow=%.1e\n",
                r.err_i, r.t_M, r.t_total, isnan(r.f_rowsum) ? NaN : r.f_rowsum)
        catch e
            println("FAILED")
            showerror(stdout, e, catch_backtrace()); println()
        end
    end

    print_table(rows)
    tsv = joinpath(OUTDIR, "dibem_rbf_compress.tsv")
    tex = joinpath(OUTDIR, "tab_dibem_rbf_compress.tex")
    if !isempty(rows)
        write_tsv(tsv, rows)
        write_latex_table(tex, rows)
        println(" wrote $tsv")
        println(" wrote $tex")
        println(" $(Dates.now())")
    end
    return rows
end

if abspath(PROGRAM_FILE) == @__FILE__
    main()
end
